[global]
address = "0.0.0.0"
port = 3000

[development]
address = "0.0.0.0"
port = 3000
log_level = "debug"

[staging]
address = "0.0.0.0"
port = 3000
log_level = "normal"

[production]
address = "0.0.0.0"
port = 3000
log_level = "critical"
